export const KEYWORDS: string[] = [
  "audio",
  "block chain",
  "computer science",
  "flash",
  "unity",
  "web",
  "word press",
];

export const SUB_KEYWORDS: string[] = [
  "aframe",
  "ar",
  "axios",
  "babylon-js",
  "c#",
  "flex",
  "game-design",
  "heavy-js",
  "javascript",
  "koregrapher",
  "magic-leap",
  "magica-voxel",
  "mui",
  "mr",
  "mysql",
  "node-js",
  "pd",
  "photoshop",
  "php",
  "post-processing",
  "processing",
  "react",
  "sass",
  "shader-graph",
  "shaders",
  "strange-ioc",
  "typescript",
  "vuforia",
];
